# Generated by Django 3.2.6 on 2021-08-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nickname', models.CharField(max_length=150)),
                ('district', models.CharField(choices=[('JONGNO', '종로구'), ('YONGSAN', '용산구'), ('SEOUNGDONG', '성동구'), ('GWANGJIN', '광진구'), ('DONGDAEMUN', '동대문구'), ('JUNGNANG', '중랑구'), ('SEONGBUK', '성북구'), ('GANGBUK', '강북구'), ('DOBONG', '도봉구'), ('NOWON', '노원구'), ('EUNPYEONG', '은평구'), ('SEODAEMUN', '서대문구'), ('MAPO', '마포구'), ('YANGCHEON', '양천구'), ('GANGSEO', '강서구')], max_length=10)),
                ('town', models.CharField(choices=[('CHEONGUN', '청운효자동'), ('SAJIK', '사직동'), ('SAMCHEONG', '삼청동'), ('BUAM', '부암동'), ('PYEONGCHANG', '평창동'), ('MUAK', '무악동')], max_length=20)),
                ('agree_terms', models.BooleanField(default=False)),
                ('agree_marketing', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
