# Generated by Django 3.2.6 on 2021-08-05 16:12

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('password', models.CharField(max_length=50)),
                ('agreement', models.BooleanField(default=False)),
                ('nickname', models.CharField(max_length=20)),
                ('district', models.CharField(choices=[('JONGNO', '종로구'), ('YONGSAN', '용산구'), ('SEOUNGDONG', '성동구'), ('GWANGJIN', '광진구'), ('DONGDAEMUN', '동대문구'), ('JUNGNANG', '중랑구'), ('SEONGBUK', '성북구'), ('GANGBUK', '강북구'), ('DOBONG', '도봉구'), ('NOWON', '노원구'), ('EUNPYEONG', '은평구'), ('SEODAEMUN', '서대문구'), ('MAPO', '마포구'), ('YANGCHEON', '양천구'), ('GANGSEO', '강서구')], max_length=10)),
                ('town', models.CharField(choices=[('CHEONGUN', '청운효자동'), ('SAJIK', '사직동'), ('SAMCHEONG', '삼청동'), ('BUAM', '부암동'), ('PYEONGCHANG', '평창동'), ('MUAK', '무악동')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
