# Generated by Django 3.2.6 on 2021-08-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name', models.TextField(max_length=150, unique=True)),
                ('badge_image', models.ImageField(upload_to='')),
                ('cafename', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='drink',
            new_name='drinkname',
        ),
        migrations.RemoveField(
            model_name='visitedcafe',
            name='cafename',
        ),
        migrations.AddField(
            model_name='user',
            name='badge_taken',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_visit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='visited_cafe',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='visited_num',
            field=models.TextField(default='[]', null=True),
        ),
    ]
